const userActionStatusCode = {
    INVALID_SIGN_UP_REQ_BODY: 'UE4001', // signUp
    USER_ALREADY_REGISTERED: 'UE4002',
    INVALID_SIGN_IN_REQ_BODY: 'UE4051', // signIn
    USER_NOT_REGISTERED: 'UE4052',
    INVALID_SIGN_IN_CREDENTIALS: 'UE4053',
    INVALID_EDIT_PROFILE_REQ_BODY: 'UE4101', // editProfile
    FOLLOW_FAILED_INVALID_REQ_BODY: 'UE4151', // follow
    FOLLOW_FAILED_USER_NOT_REGISTERED: 'UE4152',
    FOLLOW_FAILED_SELF_FOLLOW: 'UE4153',
    UNFOLLOW_FAILED_INVALID_REQ_BODY: 'UE4201', // unfollow
    UNFOLLOW_FAILED_SELF_UNFOLLOW: 'UE4202',
    UNFOLLOW_FAILED_USER_NOT_REGISTERED: 'UE4203'
};

module.exports = userActionStatusCode;