const userActionStatusCode = {
    INVALID_SIGN_UP_REQ_BODY: 'UE4001',
    USER_ALREADY_REGISTERED: 'UE4002',
    INVALID_SIGN_IN_REQ_BODY: 'UE4051',
    USER_NOT_REGISTERED: 'UE4052',
    INVALID_SIGN_IN_CREDENTIALS: 'UE4053',
    INVALID_EDIT_PROFILE_REQ_BODY: 'UE4101'
};

module.exports = userActionStatusCode;