const followActionStatusCode = {
    FOLLOW_FAILED_INVALID_REQ_BODY: 'FE4151', // follow
    FOLLOW_FAILED_USER_NOT_REGISTERED: 'FE4152',
    FOLLOW_FAILED_SELF_FOLLOW: 'FE4153',
    UNFOLLOW_FAILED_INVALID_REQ_BODY: 'FE4201', // unfollow
    UNFOLLOW_FAILED_SELF_UNFOLLOW: 'FE4202',
    UNFOLLOW_FAILED_USER_NOT_REGISTERED: 'FE4203'
};

module.exports = followActionStatusCode;